// @ts-nocheck
/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function () {
  var o = function (k, v, o, l) {
      for (o = o || {}, l = k.length; l--; o[k[l]] = v);
      return o;
    },
    $V0 = [2, 57],
    $V1 = [1, 20],
    $V2 = [5, 14, 15, 19, 30, 35, 40, 45, 48, 49, 54, 58, 62, 95, 96],
    $V3 = [1, 44],
    $V4 = [1, 40],
    $V5 = [1, 43],
    $V6 = [1, 33],
    $V7 = [1, 34],
    $V8 = [1, 35],
    $V9 = [1, 36],
    $Va = [1, 37],
    $Vb = [1, 42],
    $Vc = [1, 46],
    $Vd = [14, 15, 19, 30, 35, 40, 45, 48, 49, 54, 58, 62, 95, 96],
    $Ve = [14, 15, 19, 30, 35, 45, 48, 49, 54, 58, 62],
    $Vf = [15, 18],
    $Vg = [14, 15, 19, 30, 35, 48, 49, 54, 58, 62],
    $Vh = [34, 68, 74, 76, 85, 86, 87, 88, 89, 90],
    $Vi = [23, 34, 57, 68, 69, 74, 76, 78, 80, 85, 86, 87, 88, 89, 90],
    $Vj = [1, 62],
    $Vk = [1, 63],
    $Vl = [23, 34, 57, 69, 74, 80],
    $Vm = [23, 34, 57, 68, 69, 74, 76, 78, 80, 85, 86, 87, 88, 89, 90, 93, 94],
    $Vn = [2, 52],
    $Vo = [1, 64],
    $Vp = [68, 74, 76, 78, 85, 86, 87, 88, 89, 90],
    $Vq = [57, 68, 74, 76, 85, 86, 87, 88, 89, 90],
    $Vr = [1, 78],
    $Vs = [1, 79],
    $Vt = [1, 86],
    $Vu = [34, 68, 74, 76, 80, 85, 86, 87, 88, 89, 90],
    $Vv = [23, 68, 74, 76, 85, 86, 87, 88, 89, 90],
    $Vw = [68, 69, 74, 76, 85, 86, 87, 88, 89, 90],
    $Vx = [14, 15, 19, 30, 35, 40, 45, 48, 49, 54, 58, 62],
    $Vy = [34, 80],
    $Vz = [74, 82],
    $VA = [1, 143];
  var parser = {
    trace: function trace() {},
    yy: {},
    symbols_: {
      error: 2,
      root: 3,
      program: 4,
      EOF: 5,
      program_repetition0: 6,
      statement: 7,
      mustache: 8,
      block: 9,
      rawBlock: 10,
      partial: 11,
      partialBlock: 12,
      content: 13,
      COMMENT: 14,
      CONTENT: 15,
      openRawBlock: 16,
      rawBlock_repetition0: 17,
      END_RAW_BLOCK: 18,
      OPEN_RAW_BLOCK: 19,
      helperName: 20,
      openRawBlock_repetition0: 21,
      openRawBlock_option0: 22,
      CLOSE_RAW_BLOCK: 23,
      openBlock: 24,
      block_option0: 25,
      closeBlock: 26,
      catchClause: 27,
      openInverse: 28,
      block_option1: 29,
      OPEN_BLOCK: 30,
      openBlock_repetition0: 31,
      openBlock_option0: 32,
      openBlock_option1: 33,
      CLOSE: 34,
      OPEN_INVERSE: 35,
      openInverse_repetition0: 36,
      openInverse_option0: 37,
      openInverse_option1: 38,
      openInverseChain: 39,
      OPEN_INVERSE_CHAIN: 40,
      openInverseChain_repetition0: 41,
      openInverseChain_option0: 42,
      openInverseChain_option1: 43,
      inverseAndProgram: 44,
      INVERSE: 45,
      inverseChain: 46,
      inverseChain_option0: 47,
      OPEN_ENDBLOCK: 48,
      OPEN: 49,
      hash: 50,
      expr: 51,
      mustache_repetition0: 52,
      mustache_option0: 53,
      OPEN_UNESCAPED: 54,
      mustache_repetition1: 55,
      mustache_option1: 56,
      CLOSE_UNESCAPED: 57,
      OPEN_PARTIAL: 58,
      partial_repetition0: 59,
      partial_option0: 60,
      openPartialBlock: 61,
      OPEN_PARTIAL_BLOCK: 62,
      openPartialBlock_repetition0: 63,
      openPartialBlock_option0: 64,
      exprHead: 65,
      arrayLiteral: 66,
      sexpr: 67,
      OPEN_SEXPR: 68,
      CLOSE_SEXPR: 69,
      sexpr_repetition0: 70,
      sexpr_option0: 71,
      hash_repetition_plus0: 72,
      hashSegment: 73,
      ID: 74,
      EQUALS: 75,
      OPEN_ARRAY: 76,
      arrayLiteral_repetition0: 77,
      CLOSE_ARRAY: 78,
      blockParams: 79,
      OPEN_BLOCK_PARAMS: 80,
      blockParams_repetition_plus0: 81,
      CLOSE_BLOCK_PARAMS: 82,
      path: 83,
      dataName: 84,
      STRING: 85,
      NUMBER: 86,
      BOOLEAN: 87,
      UNDEFINED: 88,
      NULL: 89,
      DATA: 90,
      pathSegments: 91,
      sep: 92,
      SEP: 93,
      PRIVATE_SEP: 94,
      CATCH: 95,
      OPEN_CATCH_PARAMS: 96,
      catchParams: 97,
      $accept: 0,
      $end: 1,
    },
    terminals_: {
      2: 'error',
      5: 'EOF',
      14: 'COMMENT',
      15: 'CONTENT',
      18: 'END_RAW_BLOCK',
      19: 'OPEN_RAW_BLOCK',
      23: 'CLOSE_RAW_BLOCK',
      30: 'OPEN_BLOCK',
      34: 'CLOSE',
      35: 'OPEN_INVERSE',
      40: 'OPEN_INVERSE_CHAIN',
      45: 'INVERSE',
      48: 'OPEN_ENDBLOCK',
      49: 'OPEN',
      54: 'OPEN_UNESCAPED',
      57: 'CLOSE_UNESCAPED',
      58: 'OPEN_PARTIAL',
      62: 'OPEN_PARTIAL_BLOCK',
      68: 'OPEN_SEXPR',
      69: 'CLOSE_SEXPR',
      74: 'ID',
      75: 'EQUALS',
      76: 'OPEN_ARRAY',
      78: 'CLOSE_ARRAY',
      80: 'OPEN_BLOCK_PARAMS',
      82: 'CLOSE_BLOCK_PARAMS',
      85: 'STRING',
      86: 'NUMBER',
      87: 'BOOLEAN',
      88: 'UNDEFINED',
      89: 'NULL',
      90: 'DATA',
      93: 'SEP',
      94: 'PRIVATE_SEP',
      95: 'CATCH',
      96: 'OPEN_CATCH_PARAMS',
    },
    productions_: [
      0,
      [3, 2],
      [4, 1],
      [7, 1],
      [7, 1],
      [7, 1],
      [7, 1],
      [7, 1],
      [7, 1],
      [7, 1],
      [13, 1],
      [10, 3],
      [16, 5],
      [9, 4],
      [9, 4],
      [9, 4],
      [24, 6],
      [28, 6],
      [39, 6],
      [44, 2],
      [46, 3],
      [46, 1],
      [26, 3],
      [8, 3],
      [8, 5],
      [8, 5],
      [11, 5],
      [12, 3],
      [61, 5],
      [51, 1],
      [51, 1],
      [65, 1],
      [65, 1],
      [67, 3],
      [67, 5],
      [50, 1],
      [73, 3],
      [66, 3],
      [79, 3],
      [20, 1],
      [20, 1],
      [20, 1],
      [20, 1],
      [20, 1],
      [20, 1],
      [20, 1],
      [84, 2],
      [92, 1],
      [92, 1],
      [83, 3],
      [83, 1],
      [91, 3],
      [91, 1],
      [27, 2],
      [27, 5],
      [97, 2],
      [97, 1],
      [6, 0],
      [6, 2],
      [17, 0],
      [17, 2],
      [21, 0],
      [21, 2],
      [22, 0],
      [22, 1],
      [25, 0],
      [25, 1],
      [29, 0],
      [29, 1],
      [31, 0],
      [31, 2],
      [32, 0],
      [32, 1],
      [33, 0],
      [33, 1],
      [36, 0],
      [36, 2],
      [37, 0],
      [37, 1],
      [38, 0],
      [38, 1],
      [41, 0],
      [41, 2],
      [42, 0],
      [42, 1],
      [43, 0],
      [43, 1],
      [47, 0],
      [47, 1],
      [52, 0],
      [52, 2],
      [53, 0],
      [53, 1],
      [55, 0],
      [55, 2],
      [56, 0],
      [56, 1],
      [59, 0],
      [59, 2],
      [60, 0],
      [60, 1],
      [63, 0],
      [63, 2],
      [64, 0],
      [64, 1],
      [70, 0],
      [70, 2],
      [71, 0],
      [71, 1],
      [72, 1],
      [72, 2],
      [77, 0],
      [77, 2],
      [81, 1],
      [81, 2],
    ],
    performAction: function anonymous(
      yytext,
      yyleng,
      yylineno,
      yy,
      yystate /* action[1] */,
      $$ /* vstack */,
      _$ /* lstack */
    ) {
      /* this == yyval */

      var $0 = $$.length - 1;
      switch (yystate) {
        case 1:
          return $$[$0 - 1];
          break;
        case 2:
          this.$ = yy.prepareProgram($$[$0]);
          break;
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
        case 21:
        case 29:
        case 30:
        case 31:
        case 32:
        case 39:
        case 40:
        case 47:
        case 48:
          this.$ = $$[$0];
          break;
        case 9:
          this.$ = {
            type: 'CommentStatement',
            value: yy.stripComment($$[$0]),
            strip: yy.stripFlags($$[$0], $$[$0]),
            loc: yy.locInfo(this._$),
          };

          break;
        case 10:
          this.$ = {
            type: 'ContentStatement',
            original: $$[$0],
            value: $$[$0],
            loc: yy.locInfo(this._$),
          };

          break;
        case 11:
          this.$ = yy.prepareRawBlock($$[$0 - 2], $$[$0 - 1], $$[$0], this._$);
          break;
        case 12:
          this.$ = { path: $$[$0 - 3], params: $$[$0 - 2], hash: $$[$0 - 1] };
          break;
        case 13:
        case 14:
          this.$ = yy.prepareBlock($$[$0 - 3], $$[$0 - 2], $$[$0 - 1], $$[$0], false, this._$);
          break;
        case 15:
          this.$ = yy.prepareBlock($$[$0 - 3], $$[$0 - 2], $$[$0 - 1], $$[$0], true, this._$);
          break;
        case 16:
          this.$ = {
            open: $$[$0 - 5],
            path: $$[$0 - 4],
            params: $$[$0 - 3],
            hash: $$[$0 - 2],
            blockParams: $$[$0 - 1],
            strip: yy.stripFlags($$[$0 - 5], $$[$0]),
          };
          break;
        case 17:
        case 18:
          this.$ = {
            path: $$[$0 - 4],
            params: $$[$0 - 3],
            hash: $$[$0 - 2],
            blockParams: $$[$0 - 1],
            strip: yy.stripFlags($$[$0 - 5], $$[$0]),
          };
          break;
        case 19:
          this.$ = { strip: yy.stripFlags($$[$0 - 1], $$[$0 - 1]), program: $$[$0] };
          break;
        case 20:
          var inverse = yy.prepareBlock($$[$0 - 2], $$[$0 - 1], $$[$0], $$[$0], false, this._$),
            program = yy.prepareProgram([inverse], $$[$0 - 1].loc);
          program.chained = true;

          this.$ = { strip: $$[$0 - 2].strip, program: program, chain: true };

          break;
        case 22:
          this.$ = { path: $$[$0 - 1], strip: yy.stripFlags($$[$0 - 2], $$[$0]) };
          break;
        case 23:
          this.$ = yy.prepareMustache(
            yy.syntax.hash($$[$0 - 1], yy.locInfo(this._$), { yy, syntax: 'expr' }),
            [],
            undefined,
            $$[$0 - 2],
            yy.stripFlags($$[$0 - 2], $$[$0]),
            this._$
          );
          break;
        case 24:
        case 25:
          this.$ = yy.prepareMustache(
            $$[$0 - 3],
            $$[$0 - 2],
            $$[$0 - 1],
            $$[$0 - 4],
            yy.stripFlags($$[$0 - 4], $$[$0]),
            this._$
          );
          break;
        case 26:
          this.$ = {
            type: 'PartialStatement',
            name: $$[$0 - 3],
            params: $$[$0 - 2],
            hash: $$[$0 - 1],
            indent: '',
            strip: yy.stripFlags($$[$0 - 4], $$[$0]),
            loc: yy.locInfo(this._$),
          };

          break;
        case 27:
          this.$ = yy.preparePartialBlock($$[$0 - 2], $$[$0 - 1], $$[$0], this._$);
          break;
        case 28:
          this.$ = {
            path: $$[$0 - 3],
            params: $$[$0 - 2],
            hash: $$[$0 - 1],
            strip: yy.stripFlags($$[$0 - 4], $$[$0]),
          };
          break;
        case 33:
          this.$ = yy.syntax.hash($$[$0 - 1], yy.locInfo(this._$), { yy, syntax: 'expr' });
          break;
        case 34:
          this.$ = {
            type: 'SubExpression',
            path: $$[$0 - 3],
            params: $$[$0 - 2],
            hash: $$[$0 - 1],
            loc: yy.locInfo(this._$),
          };

          break;
        case 35:
          this.$ = { type: 'Hash', pairs: $$[$0], loc: yy.locInfo(this._$) };
          break;
        case 36:
          this.$ = {
            type: 'HashPair',
            key: yy.id($$[$0 - 2]),
            value: $$[$0],
            loc: yy.locInfo(this._$),
          };
          break;
        case 37:
          this.$ = yy.syntax.square($$[$0 - 1], yy.locInfo(this._$), { yy, syntax: 'expr' });
          break;
        case 38:
          this.$ = yy.id($$[$0 - 1]);
          break;
        case 41:
          this.$ = {
            type: 'StringLiteral',
            value: $$[$0],
            original: $$[$0],
            loc: yy.locInfo(this._$),
          };
          break;
        case 42:
          this.$ = {
            type: 'NumberLiteral',
            value: Number($$[$0]),
            original: Number($$[$0]),
            loc: yy.locInfo(this._$),
          };
          break;
        case 43:
          this.$ = {
            type: 'BooleanLiteral',
            value: $$[$0] === 'true',
            original: $$[$0] === 'true',
            loc: yy.locInfo(this._$),
          };
          break;
        case 44:
          this.$ = {
            type: 'UndefinedLiteral',
            original: undefined,
            value: undefined,
            loc: yy.locInfo(this._$),
          };
          break;
        case 45:
          this.$ = { type: 'NullLiteral', original: null, value: null, loc: yy.locInfo(this._$) };
          break;
        case 46:
          this.$ = yy.preparePath(true, false, $$[$0], this._$);
          break;
        case 49:
          this.$ = yy.preparePath(false, $$[$0 - 2], $$[$0], this._$);
          break;
        case 50:
          this.$ = yy.preparePath(false, false, $$[$0], this._$);
          break;
        case 51:
          $$[$0 - 2].push({ part: yy.id($$[$0]), original: $$[$0], separator: $$[$0 - 1] });
          this.$ = $$[$0 - 2];
          break;
        case 52:
          this.$ = [{ part: yy.id($$[$0]), original: $$[$0] }];
          break;
        case 53:
          this.$ = {
            strip: yy.stripFlags($$[$0 - 1], $$[$0 - 1]),
            program: $$[$0],
            catch: { loc: yy.locInfo(_$[$0 - 1]), params: [] },
          };
          break;
        case 54:
          this.$ = {
            strip: yy.stripFlags($$[$0 - 4], $$[$0 - 1]),
            program: $$[$0],
            catch: {
              loc: yy.locInfo({
                first_line: _$[$0 - 4].first_line,
                first_column: _$[$0 - 4].first_column,
                last_line: _$[$0 - 1].last_line,
                last_column: _$[$0 - 1].last_column,
              }),
              params: $$[$0 - 3],
            },
          };

          break;
        case 55:
          $$[$0 - 1].push({ name: yy.id($$[$0]), loc: yy.locInfo(_$[$0]) });
          this.$ = $$[$0 - 1];
          break;
        case 56:
          this.$ = [{ name: yy.id($$[$0]), loc: yy.locInfo(_$[$0]) }];
          break;
        case 57:
        case 59:
        case 61:
        case 69:
        case 75:
        case 81:
        case 89:
        case 93:
        case 97:
        case 101:
        case 105:
        case 111:
          this.$ = [];
          break;
        case 58:
        case 60:
        case 62:
        case 70:
        case 76:
        case 82:
        case 90:
        case 94:
        case 98:
        case 102:
        case 106:
        case 110:
        case 112:
        case 114:
          $$[$0 - 1].push($$[$0]);
          break;
        case 109:
        case 113:
          this.$ = [$$[$0]];
          break;
      }
    },
    table: [
      o([5, 14, 15, 19, 30, 35, 49, 54, 58, 62], $V0, { 3: 1, 4: 2, 6: 3 }),
      { 1: [3] },
      { 5: [1, 4] },
      o([5, 40, 45, 48, 95, 96], [2, 2], {
        7: 5,
        8: 6,
        9: 7,
        10: 8,
        11: 9,
        12: 10,
        13: 11,
        24: 15,
        28: 16,
        16: 17,
        61: 19,
        14: [1, 12],
        15: $V1,
        19: [1, 23],
        30: [1, 21],
        35: [1, 22],
        49: [1, 13],
        54: [1, 14],
        58: [1, 18],
        62: [1, 24],
      }),
      { 1: [2, 1] },
      o($V2, [2, 58]),
      o($V2, [2, 3]),
      o($V2, [2, 4]),
      o($V2, [2, 5]),
      o($V2, [2, 6]),
      o($V2, [2, 7]),
      o($V2, [2, 8]),
      o($V2, [2, 9]),
      {
        20: 28,
        50: 25,
        51: 26,
        65: 29,
        66: 38,
        67: 39,
        68: $V3,
        72: 27,
        73: 30,
        74: $V4,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      {
        20: 28,
        51: 45,
        65: 29,
        66: 38,
        67: 39,
        68: $V3,
        74: $Vc,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      o($Vd, $V0, { 6: 3, 4: 47 }),
      o($Ve, $V0, { 6: 3, 4: 48 }),
      o($Vf, [2, 59], { 17: 49 }),
      {
        20: 28,
        51: 50,
        65: 29,
        66: 38,
        67: 39,
        68: $V3,
        74: $Vc,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      o($Vg, $V0, { 6: 3, 4: 51 }),
      o([5, 14, 15, 18, 19, 30, 35, 40, 45, 48, 49, 54, 58, 62, 95, 96], [2, 10]),
      {
        20: 52,
        65: 53,
        66: 38,
        67: 39,
        68: $V3,
        74: $Vc,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      {
        20: 54,
        65: 53,
        66: 38,
        67: 39,
        68: $V3,
        74: $Vc,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      {
        20: 55,
        65: 53,
        66: 38,
        67: 39,
        68: $V3,
        74: $Vc,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      {
        20: 28,
        51: 56,
        65: 29,
        66: 38,
        67: 39,
        68: $V3,
        74: $Vc,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      { 34: [1, 57] },
      o($Vh, [2, 89], { 52: 58 }),
      o([23, 34, 57, 69, 80], [2, 35], { 73: 59, 74: [1, 60] }),
      o($Vi, [2, 29]),
      o($Vi, [2, 30], { 92: 61, 93: $Vj, 94: $Vk }),
      o($Vl, [2, 109]),
      o($Vi, [2, 39]),
      o($Vi, [2, 40]),
      o($Vi, [2, 41]),
      o($Vi, [2, 42]),
      o($Vi, [2, 43]),
      o($Vi, [2, 44]),
      o($Vi, [2, 45]),
      o($Vm, [2, 31]),
      o($Vm, [2, 32]),
      o([23, 34, 57, 68, 69, 74, 76, 80, 85, 86, 87, 88, 89, 90, 93, 94], $Vn, { 75: $Vo }),
      o($Vi, [2, 50], { 92: 65, 93: $Vj, 94: $Vk }),
      { 74: $Vc, 91: 66 },
      o($Vp, [2, 111], { 77: 67 }),
      {
        20: 28,
        50: 68,
        51: 69,
        65: 29,
        66: 38,
        67: 39,
        68: $V3,
        72: 27,
        73: 30,
        74: $V4,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      o($Vq, [2, 93], { 55: 70 }),
      o($Vm, $Vn),
      {
        25: 71,
        27: 72,
        39: 76,
        40: $Vr,
        44: 77,
        45: $Vs,
        46: 73,
        48: [2, 65],
        95: [1, 74],
        96: [1, 75],
      },
      { 29: 80, 44: 81, 45: $Vs, 48: [2, 67] },
      { 13: 83, 15: $V1, 18: [1, 82] },
      o($Vh, [2, 97], { 59: 84 }),
      { 26: 85, 48: $Vt },
      o($Vu, [2, 69], { 31: 87 }),
      { 92: 61, 93: $Vj, 94: $Vk },
      o($Vu, [2, 75], { 36: 88 }),
      o($Vv, [2, 61], { 21: 89 }),
      o($Vh, [2, 101], { 63: 90 }),
      o($V2, [2, 23]),
      {
        20: 28,
        34: [2, 91],
        50: 93,
        51: 92,
        53: 91,
        65: 29,
        66: 38,
        67: 39,
        68: $V3,
        72: 27,
        73: 30,
        74: $V4,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      o($Vl, [2, 110]),
      { 75: $Vo },
      { 74: $Vc, 91: 94 },
      { 74: [2, 47] },
      { 74: [2, 48] },
      {
        20: 28,
        51: 95,
        65: 29,
        66: 38,
        67: 39,
        68: $V3,
        74: $Vc,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      { 74: [1, 96] },
      o($Vi, [2, 46], { 92: 65, 93: $Vj, 94: $Vk }),
      {
        20: 28,
        51: 98,
        65: 29,
        66: 38,
        67: 39,
        68: $V3,
        74: $Vc,
        76: $V5,
        78: [1, 97],
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      { 69: [1, 99] },
      o($Vw, [2, 105], { 70: 100 }),
      {
        20: 28,
        50: 103,
        51: 102,
        56: 101,
        57: [2, 95],
        65: 29,
        66: 38,
        67: 39,
        68: $V3,
        72: 27,
        73: 30,
        74: $V4,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      { 26: 104, 48: $Vt },
      { 26: 105, 48: $Vt },
      { 48: [2, 66] },
      o($Vg, $V0, { 6: 3, 4: 106 }),
      { 74: [1, 108], 97: 107 },
      o($Vx, $V0, { 6: 3, 4: 109 }),
      { 48: [2, 21] },
      {
        20: 110,
        65: 53,
        66: 38,
        67: 39,
        68: $V3,
        74: $Vc,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      o($Vg, $V0, { 6: 3, 4: 111 }),
      { 26: 112, 48: $Vt },
      { 48: [2, 68] },
      o($V2, [2, 11]),
      o($Vf, [2, 60]),
      {
        20: 28,
        34: [2, 99],
        50: 115,
        51: 114,
        60: 113,
        65: 29,
        66: 38,
        67: 39,
        68: $V3,
        72: 27,
        73: 30,
        74: $V4,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      o($V2, [2, 27]),
      {
        20: 116,
        65: 53,
        66: 38,
        67: 39,
        68: $V3,
        74: $Vc,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      o($Vy, [2, 71], {
        72: 27,
        20: 28,
        65: 29,
        73: 30,
        83: 31,
        84: 32,
        66: 38,
        67: 39,
        91: 41,
        32: 117,
        51: 118,
        50: 119,
        68: $V3,
        74: $V4,
        76: $V5,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
      }),
      o($Vy, [2, 77], {
        72: 27,
        20: 28,
        65: 29,
        73: 30,
        83: 31,
        84: 32,
        66: 38,
        67: 39,
        91: 41,
        37: 120,
        51: 121,
        50: 122,
        68: $V3,
        74: $V4,
        76: $V5,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
      }),
      {
        20: 28,
        22: 123,
        23: [2, 63],
        50: 125,
        51: 124,
        65: 29,
        66: 38,
        67: 39,
        68: $V3,
        72: 27,
        73: 30,
        74: $V4,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      {
        20: 28,
        34: [2, 103],
        50: 128,
        51: 127,
        64: 126,
        65: 29,
        66: 38,
        67: 39,
        68: $V3,
        72: 27,
        73: 30,
        74: $V4,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      { 34: [1, 129] },
      o($Vh, [2, 90]),
      { 34: [2, 92] },
      o($Vi, [2, 49], { 92: 65, 93: $Vj, 94: $Vk }),
      o($Vl, [2, 36]),
      o($Vm, [2, 51]),
      o($Vm, [2, 37]),
      o($Vp, [2, 112]),
      o($Vm, [2, 33]),
      {
        20: 28,
        50: 132,
        51: 131,
        65: 29,
        66: 38,
        67: 39,
        68: $V3,
        69: [2, 107],
        71: 130,
        72: 27,
        73: 30,
        74: $V4,
        76: $V5,
        83: 31,
        84: 32,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
        91: 41,
      },
      { 57: [1, 133] },
      o($Vq, [2, 94]),
      { 57: [2, 96] },
      o($V2, [2, 13]),
      o($V2, [2, 14]),
      { 48: [2, 53] },
      { 74: [1, 135], 82: [1, 134] },
      o($Vz, [2, 56]),
      { 39: 76, 40: $Vr, 44: 77, 45: $Vs, 46: 137, 47: 136, 48: [2, 87] },
      o($Vu, [2, 81], { 41: 138 }),
      { 48: [2, 19] },
      o($V2, [2, 15]),
      { 34: [1, 139] },
      o($Vh, [2, 98]),
      { 34: [2, 100] },
      { 34: [1, 140] },
      { 33: 141, 34: [2, 73], 79: 142, 80: $VA },
      o($Vu, [2, 70]),
      o($Vy, [2, 72]),
      { 34: [2, 79], 38: 144, 79: 145, 80: $VA },
      o($Vu, [2, 76]),
      o($Vy, [2, 78]),
      { 23: [1, 146] },
      o($Vv, [2, 62]),
      { 23: [2, 64] },
      { 34: [1, 147] },
      o($Vh, [2, 102]),
      { 34: [2, 104] },
      o($V2, [2, 24]),
      { 69: [1, 148] },
      o($Vw, [2, 106]),
      { 69: [2, 108] },
      o($V2, [2, 25]),
      { 34: [1, 149] },
      o($Vz, [2, 55]),
      { 48: [2, 20] },
      { 48: [2, 88] },
      o($Vy, [2, 83], {
        72: 27,
        20: 28,
        65: 29,
        73: 30,
        83: 31,
        84: 32,
        66: 38,
        67: 39,
        91: 41,
        42: 150,
        51: 151,
        50: 152,
        68: $V3,
        74: $V4,
        76: $V5,
        85: $V6,
        86: $V7,
        87: $V8,
        88: $V9,
        89: $Va,
        90: $Vb,
      }),
      o($V2, [2, 26]),
      o($V2, [2, 22]),
      { 34: [1, 153] },
      { 34: [2, 74] },
      { 74: [1, 155], 81: 154 },
      { 34: [1, 156] },
      { 34: [2, 80] },
      o($Vf, [2, 12]),
      o($Vg, [2, 28]),
      o($Vm, [2, 34]),
      o($Vg, $V0, { 6: 3, 4: 157 }),
      { 34: [2, 85], 43: 158, 79: 159, 80: $VA },
      o($Vu, [2, 82]),
      o($Vy, [2, 84]),
      o($Vd, [2, 16]),
      { 74: [1, 161], 82: [1, 160] },
      o($Vz, [2, 113]),
      o($Ve, [2, 17]),
      { 48: [2, 54] },
      { 34: [1, 162] },
      { 34: [2, 86] },
      { 34: [2, 38] },
      o($Vz, [2, 114]),
      o($Vx, [2, 18]),
    ],
    defaultActions: {
      4: [2, 1],
      62: [2, 47],
      63: [2, 48],
      73: [2, 66],
      77: [2, 21],
      81: [2, 68],
      93: [2, 92],
      103: [2, 96],
      106: [2, 53],
      111: [2, 19],
      115: [2, 100],
      125: [2, 64],
      128: [2, 104],
      132: [2, 108],
      136: [2, 20],
      137: [2, 88],
      142: [2, 74],
      145: [2, 80],
      157: [2, 54],
      159: [2, 86],
      160: [2, 38],
    },
    parseError: function parseError(str, hash) {
      if (hash.recoverable) {
        this.trace(str);
      } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
      }
    },
    parse: function parse(input) {
      var self = this,
        stack = [0],
        tstack = [],
        vstack = [null],
        lstack = [],
        table = this.table,
        yytext = '',
        yylineno = 0,
        yyleng = 0,
        recovering = 0,
        TERROR = 2,
        EOF = 1;
      var args = lstack.slice.call(arguments, 1);
      var lexer = Object.create(this.lexer);
      var sharedState = { yy: {} };
      for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
          sharedState.yy[k] = this.yy[k];
        }
      }
      lexer.setInput(input, sharedState.yy);
      sharedState.yy.lexer = lexer;
      sharedState.yy.parser = this;
      if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
      }
      var yyloc = lexer.yylloc;
      lstack.push(yyloc);
      var ranges = lexer.options && lexer.options.ranges;
      if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
      } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
      }
      function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
      }
      _token_stack: var lex = function () {
        var token;
        token = lexer.lex() || EOF;
        if (typeof token !== 'number') {
          token = self.symbols_[token] || token;
        }
        return token;
      };
      var symbol,
        preErrorSymbol,
        state,
        action,
        a,
        r,
        yyval = {},
        p,
        len,
        newState,
        expected;
      while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
          action = this.defaultActions[state];
        } else {
          if (symbol === null || typeof symbol == 'undefined') {
            symbol = lex();
          }
          action = table[state] && table[state][symbol];
        }
        if (typeof action === 'undefined' || !action.length || !action[0]) {
          var errStr = '';
          expected = [];
          for (p in table[state]) {
            if (this.terminals_[p] && p > TERROR) {
              expected.push("'" + this.terminals_[p] + "'");
            }
          }
          if (lexer.showPosition) {
            errStr =
              'Parse error on line ' +
              (yylineno + 1) +
              ':\n' +
              lexer.showPosition() +
              '\nExpecting ' +
              expected.join(', ') +
              ", got '" +
              (this.terminals_[symbol] || symbol) +
              "'";
          } else {
            errStr =
              'Parse error on line ' +
              (yylineno + 1) +
              ': Unexpected ' +
              (symbol == EOF ? 'end of input' : "'" + (this.terminals_[symbol] || symbol) + "'");
          }
          this.parseError(errStr, {
            text: lexer.match,
            token: this.terminals_[symbol] || symbol,
            line: lexer.yylineno,
            loc: yyloc,
            expected: expected,
          });
        }
        if (action[0] instanceof Array && action.length > 1) {
          throw new Error(
            'Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol
          );
        }
        switch (action[0]) {
          case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
              yyleng = lexer.yyleng;
              yytext = lexer.yytext;
              yylineno = lexer.yylineno;
              yyloc = lexer.yylloc;
              if (recovering > 0) {
                recovering--;
              }
            } else {
              symbol = preErrorSymbol;
              preErrorSymbol = null;
            }
            break;
          case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
              first_line: lstack[lstack.length - (len || 1)].first_line,
              last_line: lstack[lstack.length - 1].last_line,
              first_column: lstack[lstack.length - (len || 1)].first_column,
              last_column: lstack[lstack.length - 1].last_column,
            };
            if (ranges) {
              yyval._$.range = [
                lstack[lstack.length - (len || 1)].range[0],
                lstack[lstack.length - 1].range[1],
              ];
            }
            r = this.performAction.apply(
              yyval,
              [yytext, yyleng, yylineno, sharedState.yy, action[1], vstack, lstack].concat(args)
            );
            if (typeof r !== 'undefined') {
              return r;
            }
            if (len) {
              stack = stack.slice(0, -1 * len * 2);
              vstack = vstack.slice(0, -1 * len);
              lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
          case 3:
            return true;
        }
      }
      return true;
    },
  };
  /* generated by jison-lex 0.3.4 */
  var lexer = (function () {
    var lexer = {
      EOF: 1,

      parseError: function parseError(str, hash) {
        if (this.yy.parser) {
          this.yy.parser.parseError(str, hash);
        } else {
          throw new Error(str);
        }
      },

      // resets the lexer, sets new input
      setInput: function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
          first_line: 1,
          first_column: 0,
          last_line: 1,
          last_column: 0,
        };
        if (this.options.ranges) {
          this.yylloc.range = [0, 0];
        }
        this.offset = 0;
        return this;
      },

      // consumes and returns one char from the input
      input: function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
          this.yylineno++;
          this.yylloc.last_line++;
        } else {
          this.yylloc.last_column++;
        }
        if (this.options.ranges) {
          this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
      },

      // unshifts one char (or a string) into the input
      unput: function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
          this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
          first_line: this.yylloc.first_line,
          last_line: this.yylineno + 1,
          first_column: this.yylloc.first_column,
          last_column: lines
            ? (lines.length === oldLines.length ? this.yylloc.first_column : 0) +
              oldLines[oldLines.length - lines.length].length -
              lines[0].length
            : this.yylloc.first_column - len,
        };

        if (this.options.ranges) {
          this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
      },

      // When called from action, caches matched text and appends it on next action
      more: function () {
        this._more = true;
        return this;
      },

      // When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
      reject: function () {
        if (this.options.backtrack_lexer) {
          this._backtrack = true;
        } else {
          return this.parseError(
            'Lexical error on line ' +
              (this.yylineno + 1) +
              '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' +
              this.showPosition(),
            {
              text: '',
              token: null,
              line: this.yylineno,
            }
          );
        }
        return this;
      },

      // retain first n characters of the match
      less: function (n) {
        this.unput(this.match.slice(n));
      },

      // displays already matched input, i.e. for error messages
      pastInput: function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...' : '') + past.substr(-20).replace(/\n/g, '');
      },

      // displays upcoming input, i.e. for error messages
      upcomingInput: function () {
        var next = this.match;
        if (next.length < 20) {
          next += this._input.substr(0, 20 - next.length);
        }
        return (next.substr(0, 20) + (next.length > 20 ? '...' : '')).replace(/\n/g, '');
      },

      // displays the character position where the lexing error occurred, i.e. for error messages
      showPosition: function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join('-');
        return pre + this.upcomingInput() + '\n' + c + '^';
      },

      // test the lexed token: return FALSE when not a match, otherwise return token
      test_match: function (match, indexed_rule) {
        var token, lines, backup;

        if (this.options.backtrack_lexer) {
          // save context
          backup = {
            yylineno: this.yylineno,
            yylloc: {
              first_line: this.yylloc.first_line,
              last_line: this.last_line,
              first_column: this.yylloc.first_column,
              last_column: this.yylloc.last_column,
            },
            yytext: this.yytext,
            match: this.match,
            matches: this.matches,
            matched: this.matched,
            yyleng: this.yyleng,
            offset: this.offset,
            _more: this._more,
            _input: this._input,
            yy: this.yy,
            conditionStack: this.conditionStack.slice(0),
            done: this.done,
          };
          if (this.options.ranges) {
            backup.yylloc.range = this.yylloc.range.slice(0);
          }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
          this.yylineno += lines.length;
        }
        this.yylloc = {
          first_line: this.yylloc.last_line,
          last_line: this.yylineno + 1,
          first_column: this.yylloc.last_column,
          last_column: lines
            ? lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length
            : this.yylloc.last_column + match[0].length,
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
          this.yylloc.range = [this.offset, (this.offset += this.yyleng)];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(
          this,
          this.yy,
          this,
          indexed_rule,
          this.conditionStack[this.conditionStack.length - 1]
        );
        if (this.done && this._input) {
          this.done = false;
        }
        if (token) {
          return token;
        } else if (this._backtrack) {
          // recover context
          for (var k in backup) {
            this[k] = backup[k];
          }
          return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
      },

      // return next match in input
      next: function () {
        if (this.done) {
          return this.EOF;
        }
        if (!this._input) {
          this.done = true;
        }

        var token, match, tempMatch, index;
        if (!this._more) {
          this.yytext = '';
          this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
          tempMatch = this._input.match(this.rules[rules[i]]);
          if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
            match = tempMatch;
            index = i;
            if (this.options.backtrack_lexer) {
              token = this.test_match(tempMatch, rules[i]);
              if (token !== false) {
                return token;
              } else if (this._backtrack) {
                match = false;
                continue; // rule action called reject() implying a rule MISmatch.
              } else {
                // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                return false;
              }
            } else if (!this.options.flex) {
              break;
            }
          }
        }
        if (match) {
          token = this.test_match(match, rules[index]);
          if (token !== false) {
            return token;
          }
          // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
          return false;
        }
        if (this._input === '') {
          return this.EOF;
        } else {
          return this.parseError(
            'Lexical error on line ' +
              (this.yylineno + 1) +
              '. Unrecognized text.\n' +
              this.showPosition(),
            {
              text: '',
              token: null,
              line: this.yylineno,
            }
          );
        }
      },

      // return next match that has a token
      lex: function lex() {
        var r = this.next();
        if (r) {
          return r;
        } else {
          return this.lex();
        }
      },

      // activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
      begin: function begin(condition) {
        this.conditionStack.push(condition);
      },

      // pop the previously active lexer condition state off the condition stack
      popState: function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
          return this.conditionStack.pop();
        } else {
          return this.conditionStack[0];
        }
      },

      // produce the lexer rule set which is active for the currently active lexer condition state
      _currentRules: function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
          return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
          return this.conditions['INITIAL'].rules;
        }
      },

      // return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
      topState: function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
          return this.conditionStack[n];
        } else {
          return 'INITIAL';
        }
      },

      // alias for begin(condition)
      pushState: function pushState(condition) {
        this.begin(condition);
      },

      // return the number of states currently on the stack
      stateStackSize: function stateStackSize() {
        return this.conditionStack.length;
      },
      options: {},
      performAction: function anonymous(yy, yy_, $avoiding_name_collisions, YY_START) {
        function strip(start, end) {
          return (yy_.yytext = yy_.yytext.substring(start, yy_.yyleng - end + start));
        }

        var YYSTATE = YY_START;
        switch ($avoiding_name_collisions) {
          case 0:
            if (yy_.yytext.slice(-2) === '\\\\') {
              strip(0, 1);
              this.begin('mu');
            } else if (yy_.yytext.slice(-1) === '\\') {
              strip(0, 1);
              this.begin('emu');
            } else {
              this.begin('mu');
            }
            if (yy_.yytext) return 15;

            break;
          case 1:
            return 15;
            break;
          case 2:
            this.popState();
            return 15;

            break;
          case 3:
            this.begin('raw');
            return 15;
            break;
          case 4:
            this.popState();
            // Should be using `this.topState()` below, but it currently
            // returns the second top instead of the first top. Opened an
            // issue about it at https://github.com/zaach/jison/issues/291
            if (this.conditionStack[this.conditionStack.length - 1] === 'raw') {
              return 15;
            } else {
              strip(5, 9);
              return 18;
            }

            break;
          case 5:
            return 15;
            break;
          case 6:
            this.popState();
            return 14;

            break;
          case 7:
            return 68;
            break;
          case 8:
            return 69;
            break;
          case 9:
            if (yy.syntax.square === 'string') {
              this.unput(yy_.yytext);
              // escaped literal
              this.begin('escl');
            } else {
              return 76;
            }

            break;
          case 10:
            return 78;
            break;
          case 11:
            return 19;
            break;
          case 12:
            this.popState();
            this.begin('raw');
            return 23;

            break;
          case 13:
            return 58;
            break;
          case 14:
            return 62;
            break;
          case 15:
            return 30;
            break;
          case 16:
            return 48;
            break;
          case 17:
            this.popState();
            return 45;
            break;
          case 18:
            this.popState();
            return 45;
            break;
          case 19:
            this.popState();
            return 95;
            break;
          case 20:
            return 96;
            break;
          case 21:
            return 35;
            break;
          case 22:
            return 40;
            break;
          case 23:
            return 54;
            break;
          case 24:
            return 49;
            break;
          case 25:
            this.unput(yy_.yytext);
            this.popState();
            this.begin('com');

            break;
          case 26:
            this.popState();
            return 14;

            break;
          case 27:
            return 49;
            break;
          case 28:
            return 75;
            break;
          case 29:
            return 74;
            break;
          case 30:
            return 74;
            break;
          case 31:
            return 94;
            break;
          case 32:
            return 93;
            break;
          case 33: // ignore whitespace
            break;
          case 34:
            this.popState();
            return 57;
            break;
          case 35:
            this.popState();
            return 34;
            break;
          case 36:
            yy_.yytext = strip(1, 2).replace(/\\"/g, '"');
            return 85;
            break;
          case 37:
            yy_.yytext = strip(1, 2).replace(/\\'/g, "'");
            return 85;
            break;
          case 38:
            return 90;
            break;
          case 39:
            return 87;
            break;
          case 40:
            return 87;
            break;
          case 41:
            return 88;
            break;
          case 42:
            return 89;
            break;
          case 43:
            return 86;
            break;
          case 44:
            return 80;
            break;
          case 45:
            return 82;
            break;
          case 46:
            return 74;
            break;
          case 47:
            yy_.yytext = yy_.yytext.replace(/\\([\\\]])/g, '$1');
            this.popState();
            return 74;

            break;
          case 48:
            return 'INVALID';
            break;
          case 49:
            return 5;
            break;
        }
      },
      rules: [
        /^(?:[^\x00]*?(?=(\{\{)))/,
        /^(?:[^\x00]+)/,
        /^(?:[^\x00]{2,}?(?=(\{\{|\\\{\{|\\\\\{\{|$)))/,
        /^(?:\{\{\{\{(?=[^/]))/,
        /^(?:\{\{\{\{\/[^\s!"#%-,\.\/;->@\[-\^`\{-~]+(?=[=}\s\/.])\}\}\}\})/,
        /^(?:[^\x00]+?(?=(\{\{\{\{)))/,
        /^(?:[\s\S]*?--(~)?\}\})/,
        /^(?:\()/,
        /^(?:\))/,
        /^(?:\[)/,
        /^(?:\])/,
        /^(?:\{\{\{\{)/,
        /^(?:\}\}\}\})/,
        /^(?:\{\{(~)?>)/,
        /^(?:\{\{(~)?#>)/,
        /^(?:\{\{(~)?#\*?)/,
        /^(?:\{\{(~)?\/)/,
        /^(?:\{\{(~)?\^\s*(~)?\}\})/,
        /^(?:\{\{(~)?\s*else\s*(~)?\}\})/,
        /^(?:\{\{(~)?\s*catch\s*(~)?\}\})/,
        /^(?:\{\{(~)?\s*catch\s+as\s+\|)/,
        /^(?:\{\{(~)?\^)/,
        /^(?:\{\{(~)?\s*else\b)/,
        /^(?:\{\{(~)?\{)/,
        /^(?:\{\{(~)?&)/,
        /^(?:\{\{(~)?!--)/,
        /^(?:\{\{(~)?![\s\S]*?\}\})/,
        /^(?:\{\{(~)?\*?)/,
        /^(?:=)/,
        /^(?:\.\.)/,
        /^(?:\.(?=([=~}\s\/.)\]|])))/,
        /^(?:\.#)/,
        /^(?:[\/.])/,
        /^(?:\s+)/,
        /^(?:\}(~)?\}\})/,
        /^(?:(~)?\}\})/,
        /^(?:"(\\["]|[^"])*")/,
        /^(?:'(\\[']|[^'])*')/,
        /^(?:@)/,
        /^(?:true(?=([~}\s)\]])))/,
        /^(?:false(?=([~}\s)\]])))/,
        /^(?:undefined(?=([~}\s)\]])))/,
        /^(?:null(?=([~}\s)\]])))/,
        /^(?:-?[0-9]+(?:\.[0-9]+)?(?=([~}\s)\]])))/,
        /^(?:as\s+\|)/,
        /^(?:\|)/,
        /^(?:([^\s!"#%-,\.\/;->@\[-\^`\{-~]+(?=([=~}\s\/.)\]|]))))/,
        /^(?:\[(\\\]|[^\]])*\])/,
        /^(?:.)/,
        /^(?:$)/,
      ],
      conditions: {
        mu: {
          rules: [
            7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
            30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 48, 49,
          ],
          inclusive: false,
        },
        emu: { rules: [2], inclusive: false },
        com: { rules: [6], inclusive: false },
        raw: { rules: [3, 4, 5], inclusive: false },
        escl: { rules: [47], inclusive: false },
        INITIAL: { rules: [0, 1, 49], inclusive: true },
      },
    };
    return lexer;
  })();
  parser.lexer = lexer;
  function Parser() {
    this.yy = {};
  }
  Parser.prototype = parser;
  parser.Parser = Parser;
  return new Parser();
})();
export default parser;
